# Generated by Django 2.0.2 on 2018-03-08 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dialysisgui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
